package net.samongi.Inscription.Player;

public enum PlayerStats
{
  ALL_DAMAGE_INCREASE,
  ARROW_DAMAGE_INCREASE,
  MELEE_DAMAGE_INCREASE,
  ALL_DAMAGE_RESISTANCE_INCREASE,
  FIRE_DAMAGE_RESISTANCE_INCREASE,
  FALL_DAMAGE_RESISTANCE_INCREASE,
  ARROW_DAMAGE_RESISTANCE_INCREASE,
  MELEE_DAMAGE_RESISTANCE_INCREASE;
}
